config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :show, :create, :destroy] do
    resources :bookmarks, only: [:create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new()
    @bookmark.list = @list
    @bookmark.movie = Movie.find(params[:bookmark][:movie_id].to_i)
    @bookmark.comment = params[:bookmark][:comment]
    if @bookmark.save
      redirect_to list_path(@list)
    else
      @show_form = true
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def create
    @lists = List.all
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      @show_form = true
      render "index", status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
      <div class="container-fluid">

        <a class="navbar-brand" href="/lists">
          <%= image_tag "logo3.png", alt: "Watch list" %>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/lists">
                  My lists
                </a>
              </li>
              <li class="nav-item dropdown">
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
                </div>
              </li>
          </ul>
        </div>

      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner"
  style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
    url(https://images.pexels.com/photos/109669/pexels-photo-109669.jpeg);">
  <div class="container text-center">
    <h1>Save any kind of movies !</h1>
    <a class="btn btn-info rounded m-3" data-bs-toggle="collapse" href="#collapseForm" role="button" aria-expanded="false" aria-controls="collapseForm">
      Create a movie list
    </a>
  </div>
</div>

<div class="d-flex justify-content-center">
  <div class="collapse <%= 'show' if @show_form %> m-4 w-25 text-center" id="collapseForm">
    <%= simple_form_for(@list) do |f| %>
      <div class="form-group">
        <%= f.input :name, class: "form-control" %>
      </div>
      <%= f.submit "Submit", class: "btn btn-info"%>
    <% end %>
  </div>
</div>

<h2 class="mt-4 mx-4"> My lists (<%= @lists.count %>)</h2>
<div class="row row-cols-md-3 row-cols-lg-4 g-4 card-group mt-2 mx-4">
  <% @lists.each do |list| %>
    <div class="col">
      <div class="card-trip">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
        <div class="card-trip-infos">
            <h2><%= link_to list.name, list_path(list), class: "text-decoration-none text-dark" %></h2>
            <div>
              <%= link_to list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              <i class="fa-solid fa-trash-can text-dark"></i>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="banner"
  style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
    url(https://images.pexels.com/photos/109669/pexels-photo-109669.jpeg);">
  <span><%= @list.movies.count %> movies</span>
  <div class="container text-center">
    <h1><%= @list.name %></h1>
    <a class="btn btn-info rounded m-3" data-bs-toggle="collapse" href="#collapseForm" role="button" aria-expanded="false" aria-controls="collapseForm">
      Add a movie
    </a>
  </div>
</div>

<div class="d-flex justify-content-center">
  <div class="collapse <%= 'show' if @show_form  %> m-4 w-25 text-center" id="collapseForm">
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <div class="form-group">
        <%= f.association :movie %>
        <%= f.input :comment, class: "form-control" %>
      </div>
      <%= f.submit "Add this movie", class: "btn btn-info"%>
    <% end %>
  </div>
</div>

<div class="row row-cols-md-1 row-cols-lg-2 g-4 card-group mt-2 mx-4">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="col">
      <div class="card-movie">
        <%= image_tag bookmark.movie.poster_url, alt: bookmark.movie.title %>
        <div class="card-movie-infos">
            <div class="card-movie-title-rating">
              <h2 class="fs-5">
                <%= bookmark.movie.title %>
              </h2>
              <span class="card-movie-rating">
                <%= bookmark.movie.rating.round(1) %>
                <i class="fa-solid fa-star text-warning"></i>
              </span>
            </div>
            <p><%= bookmark.movie.overview %></p>
            <div class="card-movie-comment-delete">
              <span>
                <i class="fa-solid fa-quote-left text-dark"></i>
                <%= bookmark.comment %>
              </span>
              <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                <i class="fa-solid fa-trash-can text-dark"></i>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  <% end %>
</div>